### ISSUE TITLE
Build new image for Drupal 7.36

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#17]
hey @samos123, i've updated the master-branch to Drupal 7.36.

since this is not a security-update and can potentially break instances (though not drastically), i propose to keep the 7.35-image also in the registry until a new security-related release is published.

**Comment by samos123** [comment]
I created a tag with 7.36 version and latest will be updated to 7.36,
people who don't want to update should always specify static tags when
specifying a docker image. Next to that an upgrade of 7.35 to 7.36 is
expected to be compatible.

The 7.35 will never change for people who specified that they want 7.35, I
made it a static change. If something needs to change to the 7.35 image, we
should mark this new tag as 7.35.image1 so that previous users won't be
affected



On Fri, Apr 10, 2015 at 4:01 AM, Frank Sachsenheim <notifications@github.com

**Comment by samos123** [comment]
The build is failing and seems to be a docker hub problem: https://registry.hub.docker.com/u/samos123/drupal/build_id/13402/code/bbqwlrz7hpysfhdg6ntjbzn/

https://github.com/docker/docker/issues/10412
