### ISSUE TITLE
Option to output Drupals logs to stdout

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-drupal#18]
[This module](https://www.drupal.org/project/console_logger) looks interesting regarding that enhancement.

**Comment by samos123** [comment]
Yea using this would definelty help in the use case of a developing making changes to Drupal, themes or plugins. Default should be using apache, but using runserver of drush as a parameter could be added. How are you using this image currently?

**Comment by funkyfuture** [comment]
you mean module? i don't, i'm not usíng Drupal 8 yet at all.

do you mean `drush runserver` could achieve something similar for Drupal 7?

using `drush runserver` for a development-mode or -tag for the image looks interesting. but i don't have Drupal-dev-needs, just -hosting-needs. someone familar with Drupal-dev should sketch a useful design for a debugging-variant.

**Comment by samos123** [comment]
yea i meant module ;) i think we can close this as this is only useful for people using this image for development.

**Comment by funkyfuture** [comment]
so should we start an issue to discuss how the image can be used for Drupal-development?

**Comment by samos123** [comment]
Nah unless somebody starts using it for drupal-development we should start
the discussion. It's pointless to implement and discuss something that
nobody is gonna use.

**Comment by Sturgelose** [comment]
Well, we started using for Drupal development, and we extended it with xDebug in order to be able to debug PHP. I added it into a custom Drupal8 branch with some fixes.

I hope with some background on our use it helps a bit.

For fast development we load the whole site under /var/www/html and we sync the changes with the volume. We run compose (drupal 8.x) and drush to setup all the modules and stuff from the entrypoint.

Some comments with the use up to now: 
1. Why not using the default variables from MySQL and Postgres instead of DB_DRIVER, DB_HOST, etc.?? This way, with just a link, you can load all the info (though this will change soon with the recent changes in Docker compose and link system)
``` php
$databases = array();
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => getenv("MYSQL_ENV_MYSQL_DATABASE"),
  'username' => getenv("MYSQL_ENV_MYSQL_USER"),
  'password' => getenv("MYSQL_ENV_MYSQL_PASSWORD"),
  'host' => getenv("MYSQL_PORT_3306_TCP_ADDR"),
  'prefix' => '',
);
```
2. Automatic builds or automatize a bit more when a new docker image is created: the latest version in DockerHub is 7.39 (though there is a latest and not sure what version is inside).
3. Be able to configure the profile or the site name through ENV variables (it's just a fast change to the default setup script).
4. From another post, yes, the way to setup all the modules and download them is using drush make in Drupal 7.x. In Drupal 8.x is compose. We run it in the setup script just before installing the database :) Works quite fine.

Wasn't sure where to add this comments, but well, hope I've provided some insights!
